# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('year_of_study', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '1(магистратура)'), (6, '2(магистратура)')], null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('formula', models.TextField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_criterions', to='fls.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='CriterionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_values', to='fls.Criterion')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_study', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '1(магистратура)'), (6, '2(магистратура)')])),
                ('faculty', models.CharField(max_length=50)),
                ('person_number', models.IntegerField()),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('max', models.IntegerField()),
                ('min', models.IntegerField()),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition_params', to='fls.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='ParamValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('person_count', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_param_values', to='fls.Group')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_values', to='fls.Param')),
            ],
        ),
        migrations.AddField(
            model_name='criterionvalue',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_criterion_values', to='fls.Group'),
        ),
        migrations.AlterUniqueTogether(
            name='competition',
            unique_together=set([('name', 'description')]),
        ),
        migrations.AlterUniqueTogether(
            name='paramvalue',
            unique_together=set([('param', 'group')]),
        ),
        migrations.AlterUniqueTogether(
            name='param',
            unique_together=set([('name', 'description')]),
        ),
        migrations.AlterUniqueTogether(
            name='criterionvalue',
            unique_together=set([('criterion', 'group')]),
        ),
    ]
