# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('formula', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CriterionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fls.Criterion')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_study', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '1(магистратура)'), (6, '2(магистратура)')])),
                ('faculty', models.CharField(max_length=50)),
                ('person_number', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max', models.IntegerField()),
                ('min', models.IntegerField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fls.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='ParamValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('person_count', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fls.Group')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fls.Param')),
            ],
        ),
        migrations.AddField(
            model_name='criterionvalue',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fls.Group'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='params',
            field=models.ManyToManyField(to='fls.Param'),
        ),
        migrations.AlterUniqueTogether(
            name='paramvalue',
            unique_together=set([('param', 'group')]),
        ),
        migrations.AlterUniqueTogether(
            name='criterionvalue',
            unique_together=set([('criterion', 'group')]),
        ),
    ]
