# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition_criterions', to='fls.Competition'),
        ),
    ]
