# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0002_auto_20190228_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='year_of_study',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '1(магистратура)'), (6, '2(магистратура)')], default=1, null=True),
        ),
    ]
