# Generated by Django 2.1.7 on 2019-02-27 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0002_param_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterionvalue',
            name='competition',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='competition_criterion_values', to='fls.Competition'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='params',
            field=models.ManyToManyField(related_name='param_criterions', to='fls.Param'),
        ),
        migrations.AlterField(
            model_name='criterionvalue',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_values', to='fls.Criterion'),
        ),
        migrations.AlterField(
            model_name='criterionvalue',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_criterion_values', to='fls.Group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='param',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_params', to='fls.Competition'),
        ),
        migrations.AlterField(
            model_name='paramvalue',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_param_values', to='fls.Group'),
        ),
        migrations.AlterField(
            model_name='paramvalue',
            name='param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_values', to='fls.Param'),
        ),
        migrations.AlterUniqueTogether(
            name='criterionvalue',
            unique_together={('competition', 'criterion', 'group')},
        ),
    ]
