# Generated by Django 2.1.7 on 2019-03-12 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fls', '0004_auto_20190307_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(blank=True, choices=[(1, 'Участник'), (2, 'Жюри'), (3, 'Эксперт-организатор'), (4, 'Эксперт оценок жюри')], default=1, null=True, verbose_name='Роль')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_group', to='fls.Group', verbose_name='Группа участника')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.IntegerField(default=0)),
                ('result_value', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='param',
            name='min',
        ),
        migrations.AddField(
            model_name='competition',
            name='method_of_estimate',
            field=models.IntegerField(blank=True, choices=[(1, 'Окончательная оценка заявки'), (2, 'Попарные сравнения параметров'), (3, 'Ранжирование параметров'), (4, 'Автоматически')], default=1, null=True, verbose_name='Метод оценивания'),
        ),
        migrations.AddField(
            model_name='param',
            name='result_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition_request', to='fls.Competition', verbose_name='Конкурс'),
        ),
        migrations.AddField(
            model_name='request',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_user', to='fls.CustomUser', verbose_name='Участник'),
        ),
        migrations.AddField(
            model_name='criterionvalue',
            name='request',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='request_criterion_values', to='fls.Request'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paramvalue',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='request_param_values', to='fls.Request'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='criterionvalue',
            unique_together={('criterion', 'request')},
        ),
        migrations.AlterUniqueTogether(
            name='paramvalue',
            unique_together={('param', 'request')},
        ),
    ]
