# Generated by Django 2.1.7 on 2019-03-12 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0005_auto_20190313_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcEstimationJury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('formula', models.TextField()),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition_formula_for_jury', to='fls.Competition')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experts', to='fls.CustomUser', verbose_name='Эксперт')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_for_jury', to='fls.Param')),
            ],
        ),
        migrations.CreateModel(
            name='EstimationJury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('jury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jury', to='fls.CustomUser', verbose_name='Жюри')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_jury_values', to='fls.Request')),
            ],
        ),
        migrations.RemoveField(
            model_name='criterionvalue',
            name='group',
        ),
        migrations.RemoveField(
            model_name='paramvalue',
            name='group',
        ),
        migrations.AlterUniqueTogether(
            name='estimationjury',
            unique_together={('jury', 'request')},
        ),
    ]
