# Generated by Django 2.1.7 on 2019-03-12 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0006_auto_20190313_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightParamJury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('jury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jury2', to='fls.CustomUser', verbose_name='Жюри')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_for_jury', to='fls.Param')),
            ],
        ),
        migrations.AlterField(
            model_name='calcestimationjury',
            name='param',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='param_for_formula_jury', to='fls.Param'),
        ),
        migrations.AlterField(
            model_name='estimationjury',
            name='jury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jury1', to='fls.CustomUser', verbose_name='Жюри'),
        ),
        migrations.AlterUniqueTogether(
            name='weightparamjury',
            unique_together={('jury', 'param')},
        ),
    ]
