# Generated by Django 2.1.7 on 2019-03-13 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0007_auto_20190313_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimationjury',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Окончательная (абсолютная) оценка заявки'), (2, 'Попарное сравнение заявок'), (3, 'Попарные сравнения параметров'), (4, 'Ранжирование параметров'), (5, 'Автоматически')], default=1, null=True, verbose_name='Тип оценивания'),
        ),
        migrations.AddField(
            model_name='weightparamjury',
            name='type',
            field=models.IntegerField(blank=True, choices=[(3, 'Попарные сравнения параметров'), (4, 'Ранжирование параметров')], default=3, null=True, verbose_name='Тип оценивания'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='method_of_estimate',
            field=models.IntegerField(blank=True, choices=[(1, 'Окончательная (абсолютная) оценка заявки'), (2, 'Попарное сравнение заявок'), (3, 'Попарные сравнения параметров'), (4, 'Ранжирование параметров'), (5, 'Автоматически')], default=1, null=True, verbose_name='Метод оценивания'),
        ),
        migrations.AlterField(
            model_name='estimationjury',
            name='jury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jury_values', to='fls.CustomUser', verbose_name='Жюри'),
        ),
        migrations.AlterUniqueTogether(
            name='estimationjury',
            unique_together={('jury', 'request', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='weightparamjury',
            unique_together={('jury', 'param', 'type')},
        ),
    ]
