# Generated by Django 2.1.7 on 2019-03-19 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0010_auto_20190313_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestEstimation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Окончательная (абсолютная) оценка заявки'), (2, 'Попарное сравнение заявок'), (3, 'Попарные сравнения параметров'), (4, 'Ранжирование параметров')], default=1, verbose_name='Тип оценивания')),
                ('value', models.FloatField()),
                ('rank', models.IntegerField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_values', to='fls.Request')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='requestestimation',
            unique_together={('request', 'type')},
        ),
    ]
