# Generated by Django 2.1.7 on 2019-03-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0011_auto_20190319_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestestimation',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
