# Generated by Django 2.1.7 on 2019-03-19 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0012_auto_20190319_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='rang',
        ),
        migrations.RemoveField(
            model_name='request',
            name='result_value',
        ),
    ]
