# Generated by Django 2.1.7 on 2019-03-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0014_requestestimation_jury_formula'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requestestimation',
            unique_together={('request', 'type', 'jury_formula')},
        ),
    ]
