# Generated by Django 2.1.7 on 2019-03-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0016_auto_20190321_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='max_limit',
            field=models.IntegerField(default=10, verbose_name='Максимальный балл'),
        ),
    ]
