# Generated by Django 2.1.7 on 2019-03-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0018_auto_20190323_1035'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='param',
            unique_together={('name', 'description', 'competition')},
        ),
    ]
