# Generated by Django 2.1.7 on 2019-03-24 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0018_auto_20190323_1141'),
        ('fls', '0019_auto_20190323_1130'),
    ]

    operations = [
    ]
