# Generated by Django 2.1.7 on 2019-03-27 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0020_merge_20190324_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEnum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('for_formula', models.BooleanField()),
                ('type', models.IntegerField(blank=True, choices=[(1, 'NUMBER'), (2, 'TEXT'), (3, 'FILE'), (4, 'PHOTO'), (5, 'ENUM'), (6, 'LINK')], default=1, null=True, verbose_name='Тип данных')),
                ('enum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subparam_enum', to='fls.CustomEnum', verbose_name='Перечисление')),
            ],
        ),
        migrations.CreateModel(
            name='SubParamValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_for_file', models.CharField(max_length=100)),
                ('link_file', models.CharField(max_length=200)),
                ('sub_param_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='fls.SubParamValue')),
            ],
        ),
        migrations.CreateModel(
            name='ValuesForEnum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enum_key', models.CharField(max_length=50)),
                ('enum_value', models.FloatField(default=0)),
                ('enum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='values_for_enum', to='fls.CustomEnum', verbose_name='Перечисление')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='type_comp',
            field=models.IntegerField(blank=True, choices=[(1, 'Одиночный'), (2, 'Групповой')], default=1, null=True, verbose_name='Тип конкурса'),
        ),
        migrations.AlterField(
            model_name='param',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='competition_params', to='fls.Competition'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='param',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paramvalue',
            name='person_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subparamvalue',
            name='enum_val',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cur_value_enum_values', to='fls.ValuesForEnum'),
        ),
        migrations.AddField(
            model_name='subparamvalue',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_subparam_values', to='fls.Request'),
        ),
        migrations.AddField(
            model_name='subparamvalue',
            name='subparam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subparam_values', to='fls.SubParam'),
        ),
        migrations.AddField(
            model_name='subparam',
            name='param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subparam_params', to='fls.Param', verbose_name='Ссылка на параметр'),
        ),
        migrations.AddField(
            model_name='customenum',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition_enums', to='fls.Competition'),
        ),
        migrations.AlterUniqueTogether(
            name='valuesforenum',
            unique_together={('enum', 'enum_key', 'enum_value')},
        ),
        migrations.AlterUniqueTogether(
            name='subparamvalue',
            unique_together={('subparam', 'request')},
        ),
        migrations.AlterUniqueTogether(
            name='subparam',
            unique_together={('param', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='customenum',
            unique_together={('name', 'competition')},
        ),
    ]
