# Generated by Django 2.1.7 on 2019-03-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0021_auto_20190327_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='param',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subparamvalue',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
