# Generated by Django 2.1.7 on 2019-03-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0022_auto_20190327_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subparamvalue',
            name='value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
