# Generated by Django 2.1.7 on 2019-03-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0023_auto_20190327_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddata',
            name='header_for_file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
