# Generated by Django 2.1.7 on 2019-04-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0026_auto_20190401_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaddata',
            name='link_file',
        ),
        migrations.AddField(
            model_name='uploaddata',
            name='image',
            field=models.ImageField(default='some.jpg', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competition',
            name='max_limit',
            field=models.IntegerField(default=10, verbose_name='Максимальный балл за заявку'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название конкурса'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='type_comp',
            field=models.IntegerField(blank=True, choices=[(1, 'Одиночный'), (2, 'Групповой')], default=1, null=True, verbose_name='Тип участия'),
        ),
    ]
