# Generated by Django 2.1.7 on 2019-04-26 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0021_auto_20190412_1913'),
        ('fls', '0028_auto_20190426_0233'),
    ]

    operations = [
    ]
