# Generated by Django 2.1.7 on 2019-04-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0029_merge_20190426_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paramvalue',
            name='person_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='criterion',
            unique_together={('competition', 'name')},
        ),
    ]
