# Generated by Django 2.1.7 on 2019-05-02 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0031_request_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='criterion',
            unique_together={('competition', 'name', 'formula', 'result_formula')},
        ),
    ]
