# Generated by Django 2.1.7 on 2019-05-02 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0032_request_result_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterionWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Ручная оценка'), (2, 'Попарные сравнения параметров'), (3, 'Автоматически')], default=3, verbose_name='Тип оценивания')),
                ('weight_value', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WeightCriterionJury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, choices=[(1, 'Ручная оценка'), (2, 'Попарные сравнения параметров'), (3, 'Автоматически')], default=3, null=True, verbose_name='Тип оценивания')),
                ('value', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='paramresultweight',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='paramresultweight',
            name='param',
        ),
        migrations.AlterUniqueTogether(
            name='paramvalue',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='paramvalue',
            name='param',
        ),
        migrations.RemoveField(
            model_name='paramvalue',
            name='request',
        ),
        migrations.AlterUniqueTogether(
            name='weightparamjury',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='weightparamjury',
            name='jury',
        ),
        migrations.RemoveField(
            model_name='weightparamjury',
            name='param',
        ),
        migrations.RemoveField(
            model_name='calcestimationjury',
            name='param',
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='param',
        ),
        migrations.AddField(
            model_name='criterion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criterion',
            name='max_for_jury',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subparam',
            name='criterion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='param_criterion', to='fls.Criterion', verbose_name='Ссылка на параметр'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competition',
            name='method_of_estimate',
            field=models.IntegerField(blank=True, choices=[(1, 'Ручная оценка'), (2, 'Попарные сравнения параметров'), (3, 'Автоматически')], default=1, null=True, verbose_name='Метод оценивания'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'Участник'), (2, 'Жюри'), (3, 'Органзитор')], default=1, null=True, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='estimationjury',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Ручная оценка'), (2, 'Попарные сравнения параметров'), (3, 'Автоматически')], default=1, null=True, verbose_name='Тип оценивания'),
        ),
        migrations.AlterField(
            model_name='requestestimation',
            name='jury_formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='formula_request_values', to='fls.CalcEstimationJury'),
        ),
        migrations.AlterField(
            model_name='requestestimation',
            name='type',
            field=models.IntegerField(choices=[(1, 'Ручная оценка'), (2, 'Попарные сравнения параметров'), (3, 'Автоматически')], default=1, verbose_name='Тип оценивания'),
        ),
        migrations.AlterField(
            model_name='subparam',
            name='enum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='param_enum', to='fls.CustomEnum', verbose_name='Перечисление'),
        ),
        migrations.AlterUniqueTogether(
            name='requestestimation',
            unique_together={('request', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='subparam',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='ParamResultWeight',
        ),
        migrations.DeleteModel(
            name='ParamValue',
        ),
        migrations.DeleteModel(
            name='WeightParamJury',
        ),
        migrations.AddField(
            model_name='weightcriterionjury',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_for_jury', to='fls.Criterion'),
        ),
        migrations.AddField(
            model_name='weightcriterionjury',
            name='jury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jury2', to='fls.CustomUser', verbose_name='Жюри'),
        ),
        migrations.AddField(
            model_name='criterionweight',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_weights', to='fls.Criterion'),
        ),
        migrations.AlterUniqueTogether(
            name='weightcriterionjury',
            unique_together={('jury', 'criterion', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='criterionweight',
            unique_together={('criterion', 'type')},
        ),
    ]
