# Generated by Django 2.1.7 on 2019-05-02 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0033_auto_20190502_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subparam',
            name='param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subparam_params', to='fls.Param', verbose_name='Ссылка на параметр'),
        ),
    ]
