# Generated by Django 2.1.7 on 2019-05-02 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0034_auto_20190502_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calcestimationjury',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='calcestimationjury',
            name='expert',
        ),
        migrations.AlterUniqueTogether(
            name='param',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='param',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='requestestimation',
            name='jury_formula',
        ),
        migrations.RemoveField(
            model_name='subparam',
            name='param',
        ),
        migrations.DeleteModel(
            name='CalcEstimationJury',
        ),
        migrations.DeleteModel(
            name='Param',
        ),
    ]
