# Generated by Django 2.1.7 on 2019-05-02 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0036_auto_20190502_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimationjury',
            name='criterion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='criterion_value_for_request', to='fls.Criterion'),
            preserve_default=False,
        ),
    ]
