# Generated by Django 2.1.7 on 2019-05-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0037_estimationjury_criterion'),
        ('fls', '0032_auto_20190502_1112'),
    ]

    operations = [
    ]
