# Generated by Django 2.1.7 on 2019-05-03 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0039_auto_20190502_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightparamjury',
            name='param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_weights', to='fls.Param'),
        ),
    ]
