# Generated by Django 2.1.7 on 2019-05-03 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0040_auto_20190503_1631'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estimationjury',
            unique_together={('jury', 'request', 'type', 'criterion')},
        ),
    ]
