# Generated by Django 2.1.7 on 2019-05-04 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0042_auto_20190504_1110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestEstimation',
            new_name='AvgEstimationJury',
        ),
    ]
