# Generated by Django 2.1.7 on 2019-05-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0043_auto_20190504_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterionweight',
            name='criterion',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='max_limit',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='year_of_study',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='group',
        ),
        migrations.AddField(
            model_name='criterion',
            name='weight_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='avgestimationjury',
            unique_together={('request', 'type', 'criterion')},
        ),
        migrations.DeleteModel(
            name='CriterionWeight',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
