# Generated by Django 2.1.7 on 2019-05-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0044_auto_20190504_1246'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avgestimationjury',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='avgestimationjury',
            name='criterion',
        ),
        migrations.RemoveField(
            model_name='avgestimationjury',
            name='request',
        ),
        migrations.DeleteModel(
            name='AvgEstimationJury',
        ),
    ]
