# Generated by Django 2.1.7 on 2019-05-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0048_remove_request_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='max_for_criteria',
            field=models.IntegerField(default=10, verbose_name='Ограничение критерия'),
        ),
    ]
