# Generated by Django 2.1.7 on 2019-05-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0050_auto_20190508_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='formula',
            field=models.TextField(blank=True, null=True),
        ),
    ]
