# Generated by Django 2.1.7 on 2019-05-12 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0052_auto_20190512_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizer_for_comp', to='fls.CustomUser', verbose_name='Оранизатор конкурса'),
        ),
    ]
