# Generated by Django 2.1.7 on 2019-05-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fls', '0054_auto_20190513_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddata',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clusternumber',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Ручная оценка'), (2, 'Оценивание критериев')], default=1, null=True, verbose_name='Тип оценивания'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='jurys',
            field=models.ManyToManyField(related_name='competitions_for_jury', to='fls.CustomUser', verbose_name='Жюри конкурса'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='method_of_estimate',
            field=models.IntegerField(blank=True, choices=[(1, 'Ручная оценка'), (2, 'Оценивание критериев'), (3, 'Расчёт по формуле')], default=1, null=True, verbose_name='Метод оценивания'),
        ),
        migrations.AlterField(
            model_name='estimationjury',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Ручная оценка'), (2, 'Оценивание критериев')], default=1, null=True, verbose_name='Тип оценивания'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Новое'), (2, 'Принятое'), (3, 'Отклоненное')], default=1, null=True, verbose_name='Статус приглашения'),
        ),
    ]
