# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-22 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights', models.TextField()),
                ('deviations_sum', models.IntegerField()),
            ],
        ),
    ]
