# Generated by Django 2.1.7 on 2019-03-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0004_groupweights'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupweights',
            name='deviations_sum',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
