# Generated by Django 2.1.7 on 2019-04-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0006_auto_20190308_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='weights',
            name='ga',
            field=models.BooleanField(default=False),
        ),
    ]
